name: HGRN
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch=1.13.0
  - pytorch-cuda=11.7
  - torchvision
  - torchaudio
  - cudatoolkit=11.7
  - numpy=1.24.0
  - pandas=1.5.0
  - scikit-learn=1.2.0
  - matplotlib=3.5.3
  - networkx=3.0
  - pip
  - pip:
    - torch-geometric==2.3.1
    - torch-scatter==2.1.1+pt113cu117
    - torch-sparse==0.6.17+pt113cu117
    - torch-cluster==1.6.1+pt113cu117
    - torch-spline-conv==1.2.2+pt113cu117
    - rdkit==2022.9.5
    - pubchempy==1.0.4
    - openbabel==3.1.0
    - optparse-pretty==0.1.1 
    - pymatgen=2022.0.17   
    
