name: HGRN
channels:
  - conda-forge      
  - pytorch
dependencies:
  - python=3.11
  - pytorch=2.7.1
  - torchvision=0.22.0
  - torchaudio=2.7.1
  - numpy=2.3.1
  - pandas=2.3.1
  - scikit-learn=1.7.0
  - matplotlib=3.10.3
  - networkx=3.5
  - openbabel=3.1.1
  - pymatgen=2025.6.14
  - rdkit=2025.03.4
  - gcc=15.1.0
  - pip
  - pip:
      - torch-geometric==2.6.1
      - pubchempy==1.0.4
      - chic-lib==0.1.19
