name: EGNN311
channels:
  - conda-forge      
  - pytorch
dependencies:
  - python=3.11
  - pytorch    
  - torchvision
  - torchaudio
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - networkx
  - openbabel
  - pymatgen
  - rdkit
  - gcc
  - pip
  - pip:
      - torch-geometric
      - pubchempy
      - chic-lib
